name: "infidelity_predictor"
version: "1.0.0"
config-version: 2

profile: "infidelity_predictor"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  infidelity_predictor:
    +schema: raw

models:
  infidelity_predictor:
    staging:
      +materialized: view
      +schema: staging
    dimensions:
      +materialized: table
      +schema: dimensions
    facts:
      +materialized: table
      +schema: facts
    marts:
      +materialized: table
      +schema: marts
